import './globals.css'
import { Header } from '@/components/Header/Header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `Dang Lam's Portfolio`,
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <div className='max-w-screen-2xl mx-auto px-8'>{children}</div>
      </body>
    </html>
  )
}
