import './globals.css'
import { Header } from '@/components/Header/Header'
import { Inter, Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: [
    '400',
    '100',
    '200',
    '300',
    '500',
    '600',
    '700',
    '800',
    '900',
    '400',
    '100',
    '200',
    '300',
    '500',
    '600',
    '700',
    '800',
    '900'
  ]
})

export const metadata = {
  title: `Dang Lam's Portfolio`,
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <div className='max-w-screen-2xl mx-auto px-16'>{children}</div>
      </body>
    </html>
  )
}
